DROP TABLE W_DZIEN CASCADE CONSTRAINTS;
DROP TABLE F_A CASCADE CONSTRAINTS;
DROP TABLE W_PRODUKT CASCADE CONSTRAINTS;
DROP TABLE W_PANSTWO CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_DZIEN_ID_DNIA;
DROP TRIGGER T_SET_DZIEN_ID_DNIA_1;
DROP PROCEDURE P_DZIEN;
DROP PROCEDURE P_PRODUKT;
DROP PROCEDURE P_PANSTWO;
DROP PROCEDURE P_F_A;


--TABELA DZIEN 
CREATE TABLE W_DZIEN
(
    ID_DNIA NUMBER(5) PRIMARY KEY,
    DATA DATE,
    DZIEN NUMBER(2),
    MIESIAC NUMBER(2),
    NAZWA_MIESIACA VARCHAR2(15),
    ROK NUMBER(4),
    DZIEN_TYGODNIA NUMBER(1),
    DZIEN_ROKU NUMBER(3),
    CZY_WEEKEND NUMBER(1),
    NR_TYG_ROKU NUMBER(2),
    KWARTAL NUMBER(1),
    NAZWA_KWARTALU VARCHAR2(10)
);

--SEKWENCJA DO TABELI  DZIEÑ
CREATE SEQUENCE SEQ_DZIEN_ID_DNIA;

--WYZWALACZ DO TABELI DZIEÑ
CREATE OR REPLACE TRIGGER T_SET_DZIEN_ID_DNIA_1
BEFORE INSERT
ON W_DZIEN
FOR EACH ROW
BEGIN
    :NEW.ID_DNIA:=SEQ_DZIEN_ID_DNIA.NEXTVAL;
END;

--TABELA PRODUKT 
CREATE TABLE W_PRODUKT
(
          ID_PRODUKTU NUMBER(4) PRIMARY KEY,
          NAZWA VARCHAR2(40)
);

--TABELA PANSTWO
CREATE TABLE W_PANSTWO
(
    ID_PANSTWA NUMBER(5) PRIMARY KEY,
    NAZWA_PANSTWA VARCHAR2(40)
);

--TABELA FAKTOW
CREATE TABLE F_A
(
          ID_PRODUKTU NUMBER(4) REFERENCES W_PRODUKT(ID_PRODUKTU),
          ID_DNIA NUMBER(5) REFERENCES W_DZIEN(ID_DNIA), 
          ID_PANSTWA NUMBER(5) REFERENCES W_PANSTWO(ID_PANSTWA),
          WARTOSC_SPRZEDAZY NUMBER(5)
);

---UZUPELNIAMY TABELE W_DZIEN
CREATE OR REPLACE PROCEDURE  P_DZIEN IS

BEGIN
 MERGE 
          INTO W_DZIEN W
          USING (SELECT 
          DATA_ZAMOWIENIA DATA,
          EXTRACT(DAY FROM DATA_ZAMOWIENIA) DZIEN,
          EXTRACT(MONTH FROM DATA_ZAMOWIENIA) MIESIAC,
          EXTRACT(YEAR FROM DATA_ZAMOWIENIA) ROK,
          TO_CHAR(DATA_ZAMOWIENIA, 'MONTH') NAZWA_MIESIAC,
          TO_NUMBER(TO_CHAR(DATA_ZAMOWIENIA, 'D')) NR_DNIA_TYG,
          TO_NUMBER(TO_CHAR(DATA_ZAMOWIENIA, 'DDD')) NR_DNIA_ROKU,
          CASE WHEN TO_CHAR(DATA_ZAMOWIENIA, 'D') IN (6,7) 
          THEN 1 ELSE 0 
          END CZY_WEEKEND,
          TO_NUMBER(TO_CHAR(DATA_ZAMOWIENIA, 'WW')) NR_TYG_ROKU,
          TO_NUMBER(TO_CHAR(DATA_ZAMOWIENIA, 'Q'))KWARTAL,
           CASE WHEN TO_CHAR(DATA_ZAMOWIENIA, 'Q') IN (1) 
           THEN 'KWARTAL1' 
           ELSE (CASE WHEN TO_CHAR(DATA_ZAMOWIENIA, 'Q') IN (2) THEN 'KWARTAL2' 
                    ELSE (CASE WHEN TO_CHAR(DATA_ZAMOWIENIA, 'Q') IN (3) THEN 'KWARTAL3' 
                              ELSE 'KWARTAL2' END) END)
          END NAZWA_KWARTALU
          FROM ZAMOWIENIE
          GROUP BY DATA_ZAMOWIENIA) A
          ON (W.DATA=A.DATA)
          WHEN NOT MATCHED THEN INSERT(W.DATA,W.DZIEN, W.MIESIAC, W.ROK, W.NAZWA_MIESIACA, W.DZIEN_TYGODNIA, W.DZIEN_ROKU, 
          W.CZY_WEEKEND, W.NR_TYG_ROKU, W.KWARTAL, W.NAZWA_KWARTALU)
          VALUES(A.DATA, A.DZIEN, A.MIESIAC, A.ROK, A.NAZWA_MIESIAC, A.NR_DNIA_TYG, A.NR_DNIA_ROKU, A.CZY_WEEKEND, A.NR_TYG_ROKU, A.KWARTAL, A.NAZWA_KWARTALU) ;
END;

EXECUTE P_DZIEN;

---UZUPELNIAMY TABELE W_PRODUKT
CREATE OR REPLACE PROCEDURE  P_PRODUKT IS

BEGIN
MERGE 
          INTO W_PRODUKT P 
          USING(
                    SELECT ID_PRODUKTU, NAZWA
                    FROM PRODUKT) B
          ON(P.ID_PRODUKTU=B.ID_PRODUKTU)
          WHEN NOT MATCHED THEN INSERT(P.ID_PRODUKTU, P.NAZWA) VALUES (B.ID_PRODUKTU, B.NAZWA);
END;

EXECUTE P_PRODUKT;


--UZUPELNIAMY TABELE W_PANSTWA
CREATE OR REPLACE PROCEDURE  P_PANSTWO IS

BEGIN
MERGE 
          INTO W_PANSTWO P
          USING(
                    SELECT ID_PANSTWA, NAZWA
                    FROM PANSTWO) C
          ON(P.ID_PANSTWA=C.ID_PANSTWA)
          WHEN NOT MATCHED THEN INSERT(P.ID_PANSTWA, P.NAZWA_PANSTWA) VALUES (C.ID_PANSTWA, C.NAZWA);
END;

EXECUTE P_PANSTWO;



-- UZUPELNIENIE TABELI FAKTOW F_A
CREATE OR REPLACE PROCEDURE P_F_A AS
BEGIN 

MERGE
          INTO F_A F
          USING(
                    SELECT WD.ID_DNIA ID_DNIA, WPR.ID_PRODUKTU  ID_PRODUKTU, WP.ID_PANSTWA ID_PANSTWA,
                              SUM(M.CENA*SZ.ILOSC) WARTOSC 
                    FROM MAGAZYN M JOIN PRODUKT P ON M.ID_PRODUKTU = P.ID_PRODUKTU
                              JOIN W_PRODUKT WPR ON P.NAZWA = WPR.NAZWA
                              JOIN SZCZEGOLY_ZAMOWIENIA SZ ON P.ID_PRODUKTU = SZ.ID_PRODUKTU
                              JOIN ZAMOWIENIE Z ON SZ.ID_ZAMOWIENIA = Z.ID_ZAMOWIENIA
                              JOIN SKLEP S ON Z.ID_SKLEPU = S.ID_SKLEPU
                              JOIN PANSTWO PA ON S.PANSTWO = PA.ID_PANSTWA
                              JOIN W_PANSTWO WP ON PA.NAZWA = WP.NAZWA_PANSTWA
                              JOIN W_DZIEN WD 
                              ON (WD.DATA=Z.DATA_ZAMOWIENIA)
          GROUP BY WD.ID_DNIA, WPR.ID_PRODUKTU, WP.ID_PANSTWA) A
          ON(F.ID_DNIA=A.ID_DNIA AND F.ID_PRODUKTU=A.ID_PRODUKTU AND F.ID_PANSTWA=A.ID_PANSTWA )
          WHEN NOT MATCHED THEN INSERT(F.ID_PRODUKTU, F.ID_DNIA, F.ID_PANSTWA, F.WARTOSC_SPRZEDAZY) 
          VALUES(A.ID_PRODUKTU, A.ID_DNIA, A.ID_PANSTWA, A.WARTOSC);

END;

EXECUTE P_F_A;

DELETE FROM F_A;

